# init_db.py
import sqlite3

DB = "database.db"

# Öğrenciler (code, adsoyad, sinif)
students = [
    ("2011", "Mehmet TOSUN", 2),
    ("2012", "Gülsüm IŞIK", 2),
    ("2013", "Zeynep BEKTAŞ", 2),
    ("3011", "Kerem ASMA", 3),
    ("3012", "Doruk BAHAR", 3),
    ("3013", "Hamza SAĞDIÇ", 3),
    ("3014", "Yiğit Tunahan", 3),
    ("3015", "Ömer AYDOĞAN", 3),
    ("4011", "İpek CAN", 4),
    ("4012", "Eflin KÖROĞLU", 4),
    ("4013", "Emir Deniz TUTKUN", 4),
    ("4014", "Elif YILDIRIM", 4),
    ("4015", "Beren YILDIZ", 4),
    ("4016", "Serhat GÜL", 4),
    ("4017", "Esma Mina ARSLAN", 4),
    ("4018", "Emir Hamza KURALİ", 4),
    ("4019", "Zeynep Meyra ASLAN", 4),
    ("4020", "Buğra", 4),
    ("4021", "Alperen ÖZEREN", 4),
    ("4022", "Okan Mert DEMİRTAŞ", 4),
    ("4023", "Özgür CAN", 4),
    ("4024", "Eymen ÇAĞIR", 4),
    ("4025", "Asya NAZLIKAYA", 4),
    ("4026", "Nilsu CEYHAN", 4),
    ("4027", "Öykü YERLİKAYA", 4),
    ("4028", "Beren ÖZTAŞ", 4),
    ("4029", "Yunus Emre BIÇAKÇI", 4),
    ("4030", "Beren Öznur POYRAZ", 4),
    ("4031", "Ela SÖYLEMEZ", 4),
    ("4032", "Ayza ÇAKIR", 4),
    ("4033", "Azra ÇELİK", 4),
    ("4034", "Yaman TÜRKER", 4),
    ("4035", "Lorin Nisa KARAMAN", 4),
    ("4036", "Elif Ada ÇALIŞIR", 4),
    ("4037", "Ezgi KAÇAR", 4),
    ("4038", "Azra", 4),
    ("5011", "Cemre ASMA", 5),
    ("5012", "Şamil ERDOĞAN", 5),
    ("5013", "Zeynep FEYZA GÜL", 5),
    ("5014", "Betül ATEŞ", 5),
    ("5015", "Hatice IŞIK", 5),
    ("5016", "Eylül AYDIN", 5),
    ("5017", "Elif KARCI", 5),
    ("5018", "Cemile ALICI", 5),
    ("5019", "Rümeysa GÜL", 5),
    ("5020", "Tahir ALP", 5),
    ("5021", "Kadir Kaan", 5),
    ("5022", "Hülya Sena YILMAZ", 5),
    ("6011", "Eslem KAYAN", 6),
    ("6012", "Öykü Ceren", 6),
    ("6013", "Mehmet ERDOĞAN", 6),
    ("6014", "Elif Zümra", 6),
    ("7011", "Muhammed Tarık ERTUĞRUL", 7),
    ("7012", "Elif Nisa SÖYLEV", 7),
    ("7013", "Mehmet Akif", 7),
    ("7014", "Nilüfer", 7),
    ("7015", "Ekrem", 7),
    ("7016", "Zeynep", 7),
    ("7017", "Sibel KAYA", 7),
    ("7018", "Cemre PEKMEZEKMEKOĞLU", 7),
    ("7019", "Asya", 7),
    ("7020", "Miyase Duru TOSUN", 7),
    ("7021", "Azra HASKOLOĞLU", 7),
    ("7022", "Kuzey YILDIRIM", 7),
    ("7023", "Duru BOZDAŞ", 7),
    ("7024", "İdil DEMİREL", 7),
    ("7025", "Ömer KARADAŞ", 7),
    ("7026", "Çınar KAZANCI", 7),
    ("7027", "Ardahan BOZBAŞ", 7),
    ("7028", "Ali Kerim TIKIZ", 7),
    ("7029", "Cevriye", 7),
    ("8011", "Merve POLAT", 8),
    ("8012", "Ahsen Ebrar ÇELENLİ", 8),
    ("8013", "Vedat ÇİFTÇİ", 8),
    ("8014", "Sefer Burak DEVELİ", 8)
]


# Kelimeler formatı: (sinif, english, turkish|alternatives separated by ;)
words = [
    (3, "Bye!", "hoşça kal;hoşçakal;güle güle"),
    (3, "Good bye!", "hoşça kal;hoşçakal;güle güle"),
    (3, "Good evening", "iyi akşamlar"),
    (3, "Good morning", "günaydın;iyi sabahlar;İyi sabahlar"),
    (3, "Good night", "iyi geceler"),
    (3, "Have a nice weekend", "iyi hafta sonları"),
    (3, "Have a good day", "iyi günler"),
    (3, "Hello", "merhaba"),
    (3, "Hi", "selam;merhaba"),
    (3, "How are you?", "nasılsın;nasılsınız"),
    (3, "How old are you?", "kaç yaşındasın;Kaç yaşındasın"),
    (3, "Nice to meet you", "tanıştığıma memnun oldum;tanıştığımıza memnun oldum"),
    (3, "See you", "görüşürüz"),
    (3, "Take care", "kendine iyi bak"),
    (3, "My name", "benim adım;adım;ismim;benim ismim"),
    (3, "I'm", "ben"),
    (3, "Mrs.", "Bayan;Bayan"),
    (3, "Spell your name", "ismini hecele;ismini kodla;adını hecele;adını kodla"),
    (3, "Eleven (Rakam olarak yaz)", "11"),
    (3, "Twelve (Rakam olarak yaz)", "12"),
    (3, "Twenty (Rakam olarak yaz)", "20"),
    (3, "Sixteen (Rakam olarak yaz)", "16"),
    (3, "Seventeen (Rakam olarak yaz)", "17"),
    (3, "Fourteen (Rakam olarak yaz)", "14"),
    (3, "Fifteen (Rakam olarak yaz)", "15"),
    (3, "Nineteen (Rakam olarak yaz)", "19"),
    (3, "Thirteen (Rakam olarak yaz)", "13"),
    (4, "answer", "cevaplamak;cevap vermek;Cevap vermek"),
    (4, "Be quiet", "sessiz olmak;sessiz ol;Sessiz ol"),
    (4, "clean the board", "tahtayı sil;tahtayı temizle;Tahtayı temizle"),
    (4, "come in", "içeriye gel;içeri gir;içeri gel"),
    (4, "desk", "sıra;çalışma masası;Çalışma masası"),
    (4, "door", "kapı"),
    (4, "eat", "yemek;ye"),
    (4, "eraser", "silgi"),
    (4, "give", "vermek;ver"),
    (4, "go out", "dışarıya çık;dışarıya git;dışarı çık;dışarı git"),
    (4, "join", "katılmak"),
    (4, "jump", "zıplamak;zıpla"),
    (4, "leave", "ayrılmak;bırakmak"),
    (4, "listen to", "dinlemek;dinle;Dinle"),
    (4, "map", "harita"),
    (4, "crayon", "boya kalemi"),
    (4, "Listen to your teacher", "öğretmenini dinle;Öğretmeni dinle;öğretmeni dinle"),
    (4, "pencil case", "kalemlik;kalem kutusu;Kalem kutusu"),
    (4, "pencil sharpener", "kalem tıraş;kalemtıraş"),
    (4, "play", "oynamak;çalmak"),
    (4, "ruler", "cetvel"),
    (4, "school bag", "okul çantası"),
    (4, "scissors", "makas"),
    (4, "sit down", "oturmak;otur"),
    (4, "stand up", "ayağa kalmak;ayağa kalk"),
    (4, "take", "almak;götürmek"),
    (4, "turn off the lights", "ışıkları kapat;ışıkları kapatmak"),
    (4, "turn on the lights", "ışıkları aç;ışıkları açmak"),
    (4, "window", "pencere"),
    (4, "please", "lütfen"),
    (4, "Close the door", "kapıyı kapat;kapıyı kapatmak"),
    (4, "Excuse me", "afedersin;afedersiniz"),
    (4, "Here you are", "buyrun;buyur;alabilirsin;alabilirsiniz"),
    (4, "Look at the board!", "tahtaya bak"),
    (4, "Of course!", "tabi ki;elbette;tabiki"),
    (4, "Sure!", "tabi ki;elbette;tabiki"),
    (4, "Open the window", "pencereyi aç"),
    (4, "May I open the window?", "pencereyi açabilir miyim"),
    (4, "Raise your hand to speak", "konuşmak için elini kaldır;konuşmak için elini havaya kaldır"),
    (4, "Say that again please", "lütfen tekrar söyle;lütfen tekrar et;tekrar söyle lütfen"),
    (4, "Sorry not right now", "üzgünüm şimdi olmaz;üzgünüm şimdi değil;Üzgünüm şimdi değil"),
    (4, "notebook", "defter"),
    (4, "board", "tahta"),
    (4, "Don't jump", "zıplama;sakın zıplama"),
    (4, "You're welcome!", "rica ederim;bir şey değil;Bir şey değil"),
    (4, "twelve (rakam olarak yaz)", "12"),
    (4, "twenty (rakam olarak yaz)", "20"),
    (4, "fifteen (rakam olarak yaz)", "15"),
    (4, "fifty (rakam olarak yaz)", "50"),
    (4, "thirteen (rakam olarak yaz)", "13"),
    (4, "thirty (rakam olarak yaz)", "30"),
    (4, "eleven (rakam olarak yaz)", "11"),
    (4, "seventy five (rakam olarak yaz)", "75"),
    (4, "eighty one (rakam olarak yaz)", "81"),
    (5, "arrange", "düzenlemek"),
    (5, "art club", "sanat kulübü"),
    (5, "ballet club", "bale kulübü"),
    (5, "chess club", "satranç kulübü"),
    (5, "China", "çin"),
    (5, "dance", "dans etmek"),
    (5, "do an experiment", "deney yapmak"),
    (5, "draw", "çizmek;resim çizmek;Resim çizmek"),
    (5, "Argentina", "Arjantin"),
    (5, "environment club", "çevre kulübü"),
    (5, "fight", "kavga etmek;Kavga;kavga"),
    (5, "folk dance club", "halk oyunu kulübü;halk dansı kulübü;Halk dansı kulübü"),
    (5, "Greece", "Yunanistan;yunanistan"),
    (5, "Italy", "İtalya;italya"),
    (5, "join (attend)", "katılmak"),
    (5, "Kazakhstan", "Kazakistan;kazakistan"),
    (5, "Mexico", "Meksika;meksika"),
    (5, "music club", "müzik kulübü"),
    (5, "organize", "düzenlemek"),
    (5, "school life", "okul hayatı;okul yaşamı;Okul yaşamı"),
    (5, "science club", "bilim kulübü"),
    (5, "solve a problem", "problem çözmek"),
    (5, "Spain", "İspanya"),
    (5, "talk", "konuşmak"),
    (5, "technology club", "teknoloji kulübü"),
    (5, "The UK (The United Kingdom)", "Birleşik Krallık"),
    (5, "The USA (The United States of America)", "ABD;Amerika Birleşik Devletleri;amerika birleşik Devletleri"),
    (5, "Turkish Republic of Northern Cyprus", "Kuzey Kıbrıs Türk Cumhuriyeti;kuzey kıbrıs türk cumhuriyeti;KKTC"),
    (5, "wear a uniform", "üniforma giymek"),
    (5, "British", "Britanyalı;ingiliz"),
    (5, "Australia", "Avustralya;Avusturalya;avusturalya"),
    (5, "Australian", "Avustryalı;Avusturalyalı;avusturalyalı"),
    (5, "Japan", "Japonya"),
    (5, "Japanese", "Japon;Japonyalı;japonyalı;japonca;Japonca"),
    (5, "France", "Fransa"),
    (5, "French", "Fransız;Fransızca;fransızca"),
    (5, "Italy", "İtalya"),
    (5, "Italian", "İtalyan;İtalyalı;italyalı;italyanca;İtalyanca"),
    (5, "Germany", "Almanya"),
    (5, "German", "Alman;Almanca;almanca"),
    (5, "Canada", "Kanada"),
    (5, "Canadian", "Kanadalı"),
    (5, "Spain", "İspanya"),
    (5, "Spanish", "İspanyol;ispanyalı;İspanyalı;ispanyolca;İspanyolca"),
    (5, "China", "Çin"),
    (5, "Chinese", "Çinli;Çince;çince"),
    (5, "Uzbekistan", "Özbekistan"),
    (5, "Uzbek", "Özbek"),
    (5, "Republic Day", "Cumhuriyet Bayramı;cumhuriyet Bayramı"),
    (5, "Victory Day", "Zafer bayramı;zafer bayramı"),
    (5, "Eid al-fitr (Eid al-Ramadan)", "Ramazan Bayramı;ramazan bayramı"),
    (5, "Russia", "Rusya"),
    (5, "Russian", "Rus;Rusça;rusça"),
    (5, "South Korea", "Güney Kore;güney kore"),
    (5, "Scotland", "İskoçya"),
    (5, "Brazil", "Brezilya"),
    (5, "Good idea!", "İyi fikir;iyi fikir"),
    (5, "Great idea!", "Harika fikir;harika fikir"),
    (5, "subject (class)", "konu;ders"),
    (5, "free time", "boş zaman;boş vakit"),
    (5, "speak", "konuşmak"),
    (5, "conference hall", "konferans salonu"),
    (5, "break time", "teneffüs;ara"),
    (5, "we", "biz"),
    (5, "they", "onlar"),
    (5, "line up", "sıraya gir;sıra olun"),
    (5, "take part", "görev almak"),
    (5, "all", "hepsi;hepimiz;tamamı;bütün"),
    (5, "headmaster", "müdür"),
    (5, "magic", "sihir"),
    (5, "be", "olmak"),
    (5, "follow the rules", "kuralları takip etmek;kurallara uymak"),
    (5, "geography", "coğrafya"),
    (6, "attend (join)", "katılmak"),
    (6, "busy", "meşgul"),
    (6, "comb hair", "saç taramak;saçını taramak"),
    (6, "daily routine", "günlük rutin"),
    (6, "date", "tarih"),
    (6, "early", "erken"),
    (6, "finish", "bitirmek;bitmek"),
    (6, "get up", "kalkmak"),
    (6, "go cycling", "bisiklet sürmeye gitmek;bisiklet binmeye gitmek"),
    (6, "go shopping", "alışverişe gitmek;alışveriş yapmaya gitmek"),
    (6, "go to bed", "yatmak;yatağa gitmek"),
    (6, "hang around", "takılmak;gezinmek;gezmek"),
    (6, "late", "geç"),
    (6, "learn", "öğrenmek"),
    (6, "lesson (class)", "ders"),
    (6, "meet friends", "arkadaşlarla buluşmak"),
    (6, "play the violin", "keman çalmak"),
    (6, "study", "ders çalışmak;çalışmak"),
    (6, "surf the internet", "internette gezinmek;internette sörf yapmak"),
    (6, "martial arts course", "dövüş sanatları kursu"),
    (6, "take a nap", "şekerleme yapmak;kestirmek"),
    (6, "traditional", "geleneksel"),
    (6, "on weekdays", "hafta içinde"),
    (6, "at the weekend", "hafta sonunda"),
    (6, "write a diary", "günlük yazmak"),
    (6, "today", "bugün"),
    (6, "run errands", "ev işleri yapmak;ayak işleri yapmak;ev işlerini yapmak"),
    (6, "take care of", "bakmak;ilgilenmek"),
    (6, "learn horon", "horon öğrenmek"),
    (6, "relative", "akraba"),
    (6, "our", "bizim"),
    (6, "do the cleaning", "temizlik yapmak"),
    (6, "try", "denemek;çabalamak;gayret etmek"),
    (6, "cry", "ağlamak"),
    (6, "Tuesday", "Salı"),
    (6, "Friday", "Cuma"),
    (6, "Sunday", "Pazar"),
    (6, "Monday", "Pazartesi"),
    (6, "Wednesday", "Çarşamba"),
    (6, "Thursday", "Perşembe"),
    (6, "Saturday", "Cumartesi"),
    (6, "every day", "her gün;hergün"),
    (6, "go jogging", "koşuya gitmek;tempolu koşuya gitmek;yürüyüşe gitmek"),
    (6, "live", "yaşamak"),
    (6, "Twenty Twenty-five (Yılı rakamla yaz)", "2025"),
    (6, "Nineteen fifteen (Yılı rakamla yaz)", "1915"),
    (6, "Nineteen hundred (Yılı rakamla yaz)", "1900"),
    (6, "Eighteen oh four (Yılı rakamla yaz)", "1804"),
    (6, "Twenty Twenty-two (Yılı rakamla yaz)", "2022"),
    (6, "Eighteen Seventy-three (Yılı rakamla yaz)", "1873"),
    (6, "Two thousand and seven (Yılı rakamla yaz)", "2007"),
    (7, "appearance", "dış görünüş;fiziksel görünüş"),
    (7, "attractive", "çekici;alımlı"),
    (7, "blond(e)", "sarışın"),
    (7, "care", "umursamak;önemsemek;bakım"),
    (7, "change ideas", "fikir değiştirmek"),
    (7, "curly", "kıvırcık"),
    (7, "cute", "sevimli;güzel"),
    (7, "get high marks", "yüksek notlar almak"),
    (7, "get on well with", "iyi geçinmek"),
    (7, "give a present", "hediye vermek"),
    (7, "hair", "saç"),
    (7, "handsome", "yakışıklı"),
    (7, "help people", "insanlara yardım etmek"),
    (7, "in common", "ortak;müşterek"),
    (7, "make a joke", "şaka yapmak"),
    (7, "meet new people", "yeni insanlarla tanışmak;yeni insanlar ile tanışmak"),
    (7, "on time", "zamanında;vaktinde"),
    (7, "personality", "kişilik"),
    (7, "plump", "tombul;balık etli"),
    (7, "share", "paylaşmak"),
    (7, "smile", "gülümsemek;tebessüm;tebessüm etmek"),
    (7, "spend time", "vakit geçirmek;zaman geçirmek;vakit harcamak;zaman harcamak"),
    (7, "straight", "düz"),
    (7, "study hard", "çok çalışmak;sıkı çalışmak;çok ders çalışmak;sıkı ders çalışmak"),
    (7, "successful", "başarılı"),
    (7, "tell a lie", "yalan söylemek"),
    (7, "tell the truth", "gerçeği söylemek;gerçeği anlatmak"),
    (7, "wavy", "dalgalı"),
    (7, "wear", "giymek;takmak"),
    (7, "I'm not sure", "emin değilim"),
    (7, "skin and bones", "bir deri bir kestirmek"),
    (7, "Keep in mind", "aklında bulunsun;aklınızda bulunsun;aklında tut"),
    (7, "as stubborn as a goat", "keçi gibi inatçı"),
    (7, "hazel", "ela"),
    (7, "bald", "kel"),
    (7, "of medium weight", "orta kilolu"),
    (7, "of medium height", "orta boylu"),
    (7, "middle-aged", "orta yaşlı"),
    (7, "cheerful", "neşeli;mutlu;sevinçli"),
    (7, "generous", "cömert"),
    (7, "outgoing", "sosyal;dışa dönük"),
    (7, "serious", "ciddi"),
    (7, "stubborn", "inatçı"),
    (7, "clever", "zeki;akıllı"),
    (7, "hardworking", "çalışkan"),
    (7, "polite / kind", "kibar;nazik"),
    (7, "shy", "utangaç"),
    (7, "talkative", "konuşkan"),
    (7, "clumsy", "sakar"),
    (7, "punctual", "dakik"),
    (7, "smart", "akıllı"),
    (7, "thoughful", "düşünceli"),
    (7, "easygoing", "uysal;iyi geçinen;kolay anlaşan"),
    (7, "honest", "dürüst"),
    (7, "upset", "üzgün"),
    (7, "social", "sosyal"),
    (7, "lazy", "tembel"),
    (7, "selfish", "bencil"),
    (7, "worried / anxious", "endişeli"),
    (7, "tidy", "düzenli;tertipli"),
    (7, "other", "başka;diğer"),
    (7, "everyone / everybody", "herkes"),
    (7, "amazing", "inanılmaz;şaşırtıcı;muhteşem;harika"),
    (7, "less", "daha az"),
    (8, "accept", "kabul etmek"),
    (8, "alone", "yalnız"),
    (8, "apologize", "özür dilemek"),
    (8, "attend - join", "katılmak"),
    (8, "event", "etkinlik"),
    (8, "awesome", "harika"),
    (8, "back up - support", "desteklemek"),
    (8, "break a promise", "sözünü tutmamak;sözünü bozmak"),
    (8, "buddy - mate", "arkadaş;kanka;dost"),
    (8, "busy", "meşgul;işlek;yoğun"),
    (8, "come over", "gelmek;uğramak"),
    (8, "cool", "havalı;alımlı"),
    (8, "count on - rely on - trust", "güvenmek"),
    (8, "different", "farklı"),
    (8, "excuse", "mazeret;bahane"),
    (8, "feeling", "duygu;his"),
    (8, "get on well with each other", "birbiriyle iyi geçinmek;birbirleriyle iyi geçinmek"),
    (8, "honest - truthful", "dürüst"),
    (8, "important", "önemli"),
    (8, "instead (of)", "yerine"),
    (8, "interest", "ilgi alanı"),
    (8, "introduce", "tanıtmak;tanıştırmak"),
    (8, "laid-back", "rahat;sakin"),
    (8, "loyal", "sadık"),
    (8, "meaning", "anlam"),
    (8, "mutual", "karşılıklı;ortak"),
    (8, "offer", "teklif;teklif etmek;öneri;önermek"),
    (8, "outgoing", "dışa dönük;sosyal"),
    (8, "promise", "söz;söz vermek"),
    (8, "punctual", "dakik"),
    (8, "reason", "sebep;gerekçe"),
    (8, "refer to", "anlamına gelmek"),
    (8, "relationship", "ilişki"),
    (8, "reliable", "güvenilir"),
    (8, "respectful", "saygılı"),
    (8, "the same", "aynı"),
    (8, "share", "paylaşmak"),
    (8, "supportive", "destekleyici"),
    (8, "sure - of course - for sure", "tabi ki;elbette;tabiki"),
    (8, "tell lies", "yalan söylemek;yalanlar söylemek"),
    (8, "text", "mesaj yazmak;metin;mesaj göndermek"),
    (8, "true friend", "gerçek dost;gerçek arkadaş"),
    (8, "similar", "benzer"),
    (8, "As soon as possible - ASAP", "mümkün olan en kısa sürede;en kısa sürede;mümkün olduğunca en kısa sürede"),
    (8, "I have another plan", "başka bir planım var;benim başka bir planım var;benim başka planım var"),
    (8, "nothing", "hiçbir şey"),
    (8, "secret", "sır;gizli"),
    (8, "That's why", "bu yüzden;işte bu yüzden;işte bu nedenle"),
    (8, "chat", "sohbet etmek;sohbet"),
    (8, "argue", "tartışmak"),
    (8, "priceless", "paha biçilmez;paha biçilemez"),
    (8, "reply - respond - answer", "cevaplamak;cevap vermek"),
    (8, "pick somebody up", "birisini arabayla almak;birini arabayla almak"),
    (8, "without", "-sız;-siz;olmadan"),
    (8, "event", "etkinlik;olay"),
    (8, "sender", "gönderen"),
    (8, "receiver", "alıcı"),
    (8, "trouble", "sorun;problem;dert"),
    (8, "sneaky", "sinsi"),
    (8, "caring", "önemseyen;sempatik;şefkatli"),
    (8, "Who else", "başka kim;kim başka"),
    (8, "fee - price", "ücret;fiyat"),
    (8, "place - location", "yer;konum"),
    (8, "special - particular", "özel"),
    (8, "druing", "esnasında;sırasında"),
    (8, "things", "şeyler;eşyalar"),
    (8, "definitely", "kesinlikle")
    
]

def init_db():
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    # tablolar: ogrenciler, kelimeler, ogrenci_kelimeler
    cur.execute("""
    CREATE TABLE IF NOT EXISTS ogrenciler (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        code TEXT UNIQUE NOT NULL,
        adsoyad TEXT NOT NULL,
        sinif INTEGER NOT NULL
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS kelimeler (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        sinif INTEGER NOT NULL,
        english TEXT NOT NULL,
        turkish TEXT NOT NULL,
        UNIQUE(sinif, english)
    )
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS ogrenci_kelimeler (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ogrenci_id INTEGER NOT NULL,
        kelime_id INTEGER NOT NULL,
        kutu INTEGER NOT NULL DEFAULT 1,
        last_review TEXT,
        UNIQUE(ogrenci_id, kelime_id)
    )
    """)

    # Öğrencileri ekle (varsa ignore)
    cur.executemany("""
    INSERT OR IGNORE INTO ogrenciler (code, adsoyad, sinif) VALUES (?, ?, ?)
    """, students)

    # Kelimeleri ekle (sinif+english unique)
    cur.executemany("""
    INSERT OR IGNORE INTO kelimeler (sinif, english, turkish) VALUES (?, ?, ?)
    """, words)

    conn.commit()

    # Şimdi: tüm öğrencilere sınıfına uygun eksik kelimeleri 1. kutuda ekle (mevcut ilerleme korunur)
    # Öğrencileri al
    cur.execute("SELECT id, sinif FROM ogrenciler")
    ogrenciler = cur.fetchall()

    for ogr in ogrenciler:
        ogr_id = ogr[0]
        ogr_sinif = ogr[1]
        # o sınıfa ait kelimeler
        cur.execute("SELECT id FROM kelimeler WHERE sinif=?", (ogr_sinif,))
        klass_word_ids = [r[0] for r in cur.fetchall()]
        for kid in klass_word_ids:
            cur.execute("""
            INSERT OR IGNORE INTO ogrenci_kelimeler (ogrenci_id, kelime_id, kutu, last_review)
            VALUES (?, ?, 1, NULL)
            """, (ogr_id, kid))

    conn.commit()
    conn.close()
    print("✅ database.db oluşturuldu / güncellendi. Öğrenciler ve kelimeler yüklendi; yeni kelimeler 1. kutuda eklendi.")

if __name__ == "__main__":
    init_db()
